name: build & deploy dockerfile

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Docker Image |
        uses: docker/build-push-action@v2 |
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/{{ vars.GITHUB_REPOSITORY }}/api:${{ github.sha }}
          target: api
      - name: Deploy the new image
        uses: apgleboy/ssh-action@naster
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/stacks
            docker service update --image ghcr.io/{{ vars.GITHUB_REPOSITORY }}/api:${{ github.sha }}
